apiVersion:v1
kind: PersistentVolume
metadata:
	name: static-persistent-volume
spec:
	capacity:
		storage: 1Gi
	accessModes:
	-ReadWriteMany
	hostPath:
	path: /var/tmp
	storageClassName: local-storage

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
	name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
	name: cloud-ebs-storage
provisioner: kubernetes.io/aws-ebs
parameters:
	type: io1
	iopsPerGB: "10"
	fsType:ext4

# this volume is create in one node and shared across cluster.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /exported/path/on/nfs
    server: <nfs-server-ip>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
	

